### ISSUE TITLE
react-native android build error

### ISSUE THREAD

**Issue by AzharTechversant** [souvik-ghosh/react-native-create-thumbnail#78]
Describe the bug
While compile the app getting error  * Where:
Build file '...../node_modules/react-native-create-thumbnail/android/build.gradle' line: 114

* What went wrong:
A problem occurred configuring project ':react-native-create-thumbnail'.
> Could not resolve all files for configuration ':react-native-create-thumbnail:implementation'.
   > Could not resolve com.facebook.react:react-native:+.
     Required by:
         project :react-native-create-thumbnail
      > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml'.
               > Read timed out

To Reproduce

Run the app for android with latest react native configuration

1. either npx react-native run-android or ./gradlew build in android folder

Version
"react": "18.2.0",
"react-native": "0.70.3",
"react-native-create-thumbnail": "^1.6.3"

Expected Results
![thumbnailnewissue](https://user-images.githubusercontent.com/96411269/198999717-0329c30d-9153-4fca-83ea-d4e14eb49bd0.png)

App should be compile and run on device

**Comment by sametcl2** [comment]
I have the same issue

**Comment by saif-o99** [comment]
Same here, whats wrong?

**Comment by qusaieilouti99** [comment]
Same Issue

**Comment by eltton** [comment]
Same Issue

**Comment by Anzormumladze** [comment]
Anyone know how long this problem will last?

**Comment by parthkanani93** [comment]
Same Issue

**Comment by WassimYK** [comment]
it works fine for me now

**Comment by custundag** [comment]
Same issue

**Comment by AhmadAl-Ghalban** [comment]
Same issue

**Comment by justinadkins** [comment]
Encountering this again as well, is this still due to jcenter?

**Comment by justinadkins** [comment]
Likely related to this: https://github.com/facebook/react-native/issues/35210

**Comment by Ppang0405** [comment]
+1

**Comment by hardikbhingradiya** [comment]
Please update library version to 1.6.3, its working fine for me.

**Comment by marcoamt** [comment]
sorry but it doesn't work for us, we are using 1.6.3 version

**Comment by DanielAraldi** [comment]
I'm having the same problem, does anyone have any news?

**Comment by DanielAraldi** [comment]
I'm using React native `0.63.4` and I had the same problem when generating the APK. I managed to solve it by adding the following code snippet in my `android/build.gradle`:
```gradle
def REACT_NATIVE_VERSION = new File(['node', '--print',"JSON.parse(require('fs').readFileSync(require.resolve('react-native/package.json'), 'utf-8')).version"].execute(null, rootDir).text.trim())

allprojects {
    configurations.all {
        resolutionStrategy {
            force "com.facebook.react:react-native:" + REACT_NATIVE_VERSION
        }
    }
    // ...
}
```

**Comment by FadiAboMsalam** [comment]
what worked for me is adding the following to **build.gradle** inside allprojects-->repositories

`        exclusiveContent {
           filter {
               includeGroup "com.facebook.react"
           }
           forRepository {
               maven {
                   url "$rootDir/../node_modules/react-native/android"
<img width="603" alt="Screenshot 2023-01-17 at 12 02 27" src="https://user-images.githubusercontent.com/12826829/212868650-f99977f4-ca2c-4903-b377-4902f686d0f5.png">

               }
           }
       }`

**Comment by bumpingChris** [comment]
We are upgrading our RN version from 0.69.7 to 0.71.7. Everything seemed fine in iOS except for react-native-create-thumbnail. We got the following error: 

`Build file ‘/XXXXXX/node_modules/react-native-create-thumbnail/android/build.gradle’ line: 115
A problem occurred configuring project ‘:react-native-create-thumbnail’.
> Could not resolve all files for configuration ‘:react-native-create-thumbnail:implementation’.
   > Could not find react-native-0.71.0-rc.0-release.aar (com.facebook.react:react-native:0.71.0-rc.0).
     Searched in the following locations:`

We then tried to apply the recommended fixes above including:
1) exclusiveContent { filter { includeGroup "com.facebook.react" } forRepository { maven { url "$rootDir/../node_modules/react-native/android" } } }

2) def REACT_NATIVE_VERSION = new File(['node', '--print',"JSON.parse(require('fs').readFileSync(require.resolve('react-native/package.json'), 'utf-8')).version"].execute(null, rootDir).text.trim())

allprojects {
    configurations.all {
        resolutionStrategy {
            // Remove this override in 0.66, as a proper fix is included in react-native itself.
            force "com.facebook.react:react-native:" + REACT_NATIVE_VERSION
        }
    }
    
We still get this type of error:

`A problem occurred configuring project ‘:react-native-create-thumbnail’.
> Could not resolve all files for configuration ‘:react-native-create-thumbnail:implementation’.
   > Could not find any matches for com.facebook.react:react-native:+ as no versions of com.facebook.react:react-native are available.
     Searched in the following locations:
       - file:/XXXXXXX/node_modules/react-native/android/com/facebook/react/react-native/maven-metadata.xml
     Required by:
         project :react-native-create-thumbnail`
         

Any suggestions would be helpful.

**Comment by justinadkins** [comment]
@bumpingChris this was resolved for the latest version of RN. Could it be that your `app/build.gradle` is incorrectly set up? There are some fairly large changes between the versions you mentioned. See example [here](https://react-native-community.github.io/upgrade-helper/?from=0.69.7&to=0.71.7#RnDiffApp-android-app-build.gradle).

**Comment by souvik-ghosh** [comment]
closing due to inactivity

**Comment by kavinder123** [comment]
minSdkVersion = 21
 compileSdkVersion = 33
 targetSdkVersion = 33
 "react-native-create-thumbnail": "^2.0.0",

still getting the same issue

**Comment by nicoladj77** [comment]
@kavinder123 did you fix it?What react native version are you using?
